### ISSUE TITLE
Typo in docs: DBBACKUP_CLEANUP_FILTER should be DBBACKUP_CLEANUP_KEEP_FILTER

### ISSUE THREAD

**Issue by quaintjames** [jazzband/django-dbbackup#430]
Typo in docs: DBBACKUP_CLEANUP_FILTER should be DBBACKUP_CLEANUP_KEEP_FILTER as per: https://github.com/jazzband/django-dbbackup/blob/2ef053cda8078817ad6872cb3719e38de3cfdaeb/dbbackup/settings.py#L20

Docs page here: https://django-dbbackup.readthedocs.io/en/master/configuration.html?highlight=DBBACKUP_CLEANUP_KEEP#dbbackup-cleanup-filter

Hopefully this helps someone!

**Comment by sergeydubak** [comment]
Hey, this is still relevant, can someone merge this fix?

**Comment by Archmonger** [comment]
Unfortunately this repo is in a stalemate due to #483 and https://github.com/jazzband/help/issues/336
