### ISSUE TITLE
performance while backing up?

### ISSUE THREAD

**Issue by fcoppey** [jazzband/django-dbbackup#431]
Hello,

I’m wondering if the website is slowing down while performing the backup as it is very slow when I do a classic mysql dump from the command line for me. would that be the same here or you do not notice a change in pages loading and API response time?

Thanks for your insight

**Comment by johnthagen** [comment]
@fcoppey In my particular use case I schedule backups (using `crontab`) during low-activity periods of time. When those activity are or if such times exist will of course vary from application to application.

**Comment by Archmonger** [comment]
Yes, performance impact is expected. However, the amount of performance impact you'll see depends on your database server's hardware.
