### ISSUE TITLE
Fail to backup MySql db file

### ISSUE THREAD

**Issue by meet1919** [jazzband/django-dbbackup#433]
`django version : 4.0.3`
`django-dbbackup version: 3.3.0`
`python version: Python 3.9.7`

**When running this command `python manage.py dbbackup` an error come:**
`ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'`

**If from `site-packages/django-dbbackup/apps.py` you replace `ugettext_lazy` with `gettext_lazy`, the above error wont come but an new error comes.**
`dbbackup.db.exceptions.CommandConnectorError: Error running:  mysqldump payupdb --quick --host=localhost --user=root --password=****`

**Comment by andreyyudin** [comment]
For what it is worth I am on 
`django version : 4.0.4`
`django-dbbackup version: 3.3.0`
`python version: Python 3.10.4`

and it worked fine after changing to `gettext_lazy`. Would be really great if `gettext_lazy` could be permanently fixed.

**Comment by chambersh1129** [comment]
Looks like this fixed with #342 which was merged into pre-release 4.0.0b0, and 4.0.2 was just released yesterday if you don't want to use the pre-release version.  Could you attempt to upgrade and verify it is fixed?

**Comment by Archmonger** [comment]
This one was fixed with version `4.0.0`.
