### ISSUE TITLE
Option delete old/specific backup

### ISSUE THREAD

**Issue by jerinpetergeorge** [jazzband/django-dbbackup#459]
# Feature Request
An option to delete old backups would be nice. This would be helpful if our storages are size sensitive (or price sensitive :wink: )

## Is your feature request related to a problem?

Yes, I wish we had an option to delete certain backups, then that would be used to delete old backups and free up the memory

## Describe the solution you'd like

Creating another management command would be nice, I think

**Comment by Archmonger** [comment]
Right now that exists in a different form.

`DBBACKUP_CLEANUP_KEEP` can be set to the maximum number of backup files you want to keep. When a backup is performed, django-dbbackup will delete the oldest files.

`DBBACKUP_CLEANUP_FILTER` can be used to change which files are allowed to be kept, if you don't want to simply cull the oldest files.

**Comment by jerinpetergeorge** [comment]
That did the trick
