### ISSUE TITLE
python-gnupg version increase breaks unencrypt_file function

### ISSUE THREAD

**Issue by chambersh1129** [jazzband/django-dbbackup#460]
# Bug Report

## Describe the bug

Latest version of python-gnupg on PyPi is 0.5.0.  The file argument for gnupg.GPG().decrypt_file has changed from "file" to "fileobj_or_path".  This is causing tests to fail with error "TypeError: GPG.decrypt_file() got an unexpected keyword argument 'file'".  

decrypt_file can be found [here](https://github.com/jazzband/django-dbbackup/blob/master/dbbackup/utils.py#L230).

Failing tests:
- dbbackup.tests.functional.test_commands.MediaRestoreCommandTest.test_encrypted
- dbbackup.tests.functional.test_commands.DbRestoreCommandTest.test_encrypted
- dbbackup.tests.commands.test_dbrestore.DbrestoreCommandRestoreBackupTest.test_decrypt
- dbbackup.tests.test_utils.Unencrypt_FileTest.test_unencrypt

If tests are failing, decryption of the backups are likely failing to for newer installs.

## To Reproduce

- create a fresh virtual environment
- install django-dbbackup requirements, including test requirements
- run tests

Alternatively, in a django project

- pip install --upgrade python-gnupg
- make an encrypted backup
- try to restore backup

## Expected behavior

Tests pass, backups are decrypted

### Django-dbbackup
- pypi: 4.0.1

### External tools

- Python: 3.10
- Django: 4.1.1
- OS: Linux, Fedora Silverblue 36

**Comment by chambersh1129** [comment]
If this gets accepted, I'd like to take a stab at fixing it.  Just want some input on whether it is better to compare versions or pin the python-gnupg version in the requirements/tests.txt file.

Compare versions pseudo-code:
`
from pgk_resources import parse_version

if parse_version(gnupg.__version__) >= parse_version("5.0.0"):
    use new fileobj_or_path
else:
    use file
`

**Comment by Archmonger** [comment]
In general, it's best to practice pin the minimum version and keep the max unpinned. I'd be okay with reviewing a PR that supports `python-gnupg>=0.5.0`.

**Comment by chambersh1129** [comment]
I'll submit a PR to address this later today, thanks for the input.
