### ISSUE TITLE
Refactor to remove tight coupling with Django??

### ISSUE THREAD

**Issue by isedwards** [jazzband/django-dbbackup#468]
# Feature Request

I'm looking for a generic Python package for database backups that I can use on all projects (not just Django).

I can't find anything suitable and I was wondering whether there may be any appetite to make django-dbbackup more loosely coupled to Django?

## Describe the solution you'd like

I've not dug deep enough to know for sure whether this is sensible, but I think I'm suggesting decoupling `BaseCommandDBConnector` and ` BaseDbBackupCommand` so that they can be used in plain Python or with other frameworks by using alternative base classes.

**Comment by Archmonger** [comment]
To answer your question: Yes this it is possible to pull out [database related features](https://github.com/jazzband/django-dbbackup/tree/master/dbbackup/db) into a separate package.

While I personally don't have plans to do this, you are free to do this [under the conditions of the license](https://github.com/jazzband/django-dbbackup/blob/master/LICENSE.txt).

However, due [a high severity issue](https://github.com/jazzband/help/issues/196) within Jazzband, it is unlikely you'll be able to pull the project into this organization.

In fact, even if I tried to pull `django-dbbackup` outside of Jazzband right now, I'd likely be blocked by the same issue.
