### ISSUE TITLE
Add arguments to [mysql] db-connector

### ISSUE THREAD

**Issue by derblub** [jazzband/django-dbbackup#477]
# Feature Request

Option to pass any optional arguments to db-connector.

## Is your feature request related to a problem?

Currently, I'm working on a mysql db, where I'm running into issues, because the default mysqldump arguments are not enough.

## Describe the solution you'd like

It would be great if we could define a list of arguments, which should be applied to the db-connector.

## Additional context

In my special case, it's needed to add `--max_allowed_packet=64M` to the mysqldump command, or else the dump is failing (binary data stored in columns).

**Comment by Archmonger** [comment]
Should be fairly simple to add this feature. Would feel more django-like for the values to be in a `settings.py` dictionary.

The dictionary values would get appended to each backend's [`cmd` variable](https://github.com/jazzband/django-dbbackup/blob/790ec8bd297ef24cddfd2618d18d243abd15437e/dbbackup/db/mongodb.py#L21).

Would you like to take a stab at PRing this?

**Comment by derblub** [comment]
I've ended up by creating my custom dump connector like this, which makes it even more flexible.

```
DBBACKUP_CONNECTOR_MAPPING = {
    'django.db.backends.mysql': 'my_app.dbbackup.MyMysqlDumpConnector',
}
```

closing.
