### ISSUE TITLE
Error when uploading DB backup to dropbox with django 4.2.14

### ISSUE THREAD

**Issue by medcherif17** [jazzband/django-dbbackup#519]
### Current Situation

Hi everyone
i use dbbackup with dropbox and since i upgraded django to 4.2.14 i am getting this error : "SuspiciousFileOperation: Detected path traversal attempt in ..."
it works fine with django 4.2.13

### System Information

Django 4.2.14
Python 3.10.11
Django-dbbackup 4.1.0

**Comment by domvie** [comment]
I had the same issue, what worked for me was changing the path from absolute to a relative path (basically only the filename)

**Comment by sergeydubak** [comment]
Try to update `django-storages` to `1.14.4`

**Comment by medcherif17** [comment]
@sergeydubak thanks it works with the update

@domvie thanks for your response, i was a bit busy so i haven't tried it
