### ISSUE TITLE
PostgreSQL connector should default to "localhost" if no HOST is provided instead of erroring.

### ISSUE THREAD

**Issue by bckohan** [jazzband/django-dbbackup#520]
### Current Situation

If HOST key is not present in the DATABASES setting dbbackup will error out.

### Proposed Actions

It is valid Django that if HOST is not present [it is assumed to be localhost](https://docs.djangoproject.com/en/stable/ref/settings/#host). 

I propose that if HOST is not present it is assumed to be localhost as the Django docs suggest.

### System Information

all systems are affected.

**Comment by sur5r** [comment]
Actually, the fix is wrong. The Django docs explicetely state that empty host string means unix domain socket connection for postgres. This also reported in #490. So the fallback for unset HOST should be `""` and not `"localhost"`.
