### ISSUE TITLE
Support new Django STORAGES setting (4.2+)

### ISSUE THREAD

**Issue by domvie** [jazzband/django-dbbackup#522]
### Feature description

Since Django 4.2 there is a new way to configure storages using the STORAGES setting. E.g.: 

```
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
          ...your_options_here
        },
    },
}
```

instead of the old `DEFAULT_FILE_STORAGE = "storages.backends.s3.S3Storage"` with global options. 

This plugin currently expects the old format and internally calls Django's deprecated `django.core.files.storage.get_storage_class` function.

**Comment by Archmonger** [comment]
Do you want to PR this?
